module.exports = Object.freeze({
  GET_ALL_APPLICATIONS: '/get/applications',
  GET_APPLICATION_DETAILS: '/get/application_details',
  ADD_AN_APPLICATION: '/post/application',
  EDIT_AN_APPLICATION: '/put/application',
  DELETE_AN_APPLICATION: '/delete/application',
  GET_ALL_MAPPED_DATABASES: '/get/databases',
  GET_DATABASE_DETAILS: '/get/database_details',
  ADD_DATABASE: '/post/database',
  EDIT_A_DATABASE: '/put/database',
  DELETE_A_DATABASE: '/delete/database',
  GET_ALL_DATABASE_TYPES: '/get/database_types',
  GET_ALL_USERS: '/get/users',
  GET_USER_DETAILS: '/get/user_details',
  ADD_AN_USER: '/post/user',
  EDIT_USER_DETAILS: '/put/user_details',
  DELETE_AN_USER: 'delete/user',
});
