export const SUCCESS = 'SUCCESS';

export const FAILURE = 'FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT';

export const LOGOUT_FAILURE = 'LOGOUT';

export const SET_USERS = 'SET_USERS';

export const ADD_USER = 'ADD_USER';

export const EDIT_USER = 'EDIT_USER';

export const DELETE_USER = 'DELETE_USER';

export const SET_APPLCIATIONS = 'SET_APPLICATIONS';

export const ADD_APPLICATION = 'ADD_APPLICATION';

export const EDIT_APPLICATION = 'EDIT_APPLICATION';

export const DELETE_APPLICATION = 'DELETE_APPLICATION';

export const SET_DATABASES = 'SET_DATABASES';

export const ADD_DATABASE = 'ADD_DATABASE';

export const EDIT_DATABASE = 'EDIT_DATABASE';

export const DELETE_DATABASE = 'DELETE_DATABASE';

export const SET_APPLICATION_SCREENS = 'SET_APPLICATION_SCREENS';

export const EDIT_APPLICATION_SCREEN_RIGHTS = 'EDIT_APPLICATION_SCREEN_RIGHTS';

export const EDIT_USER_PERMISSION_RIGHTS = 'EDIT_USER_PERMISSION_RIGHTS';

export const USER_INPUT_SUBMIT = 'USER_INPUT_SUBMIT';
