export const SUCCESS = 'SUCCESS';

export const FAILURE = 'FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const SET_DB_USER = 'SET_DB_USER';

export const REMOVE_DB_USER = 'REMOVE_DB_USER';

export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';

export const SET_USER = 'SET_USER';

export const FETCH_APPLICATIONS = 'FETCH_APPLICATIONS';

export const SET_APPLICATION = 'SET_APPLICATION';

export const FETCH_DATABASES = 'FETCH_DATABASES';

export const SET_DATABASE = 'SET_DATABASE';

export const FETCH_APPLICATION_SCREENS = 'FETCH_APPLICATION_SCREENS';

export const SET_ALL_APPLICATION_SCREEN_RIGHTS =
  'SET_ALL_APPLICATION_SCREEN_RIGHTS';

export const SET_ALL_USER_PERMISSIONS = 'SET_ALL_USER_PERMISSIONS';
