export const SUCCESS = 'SUCCESS';

export const FAILURE = 'FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const SET_DB_USER = 'SET_DB_USER';

export const REMOVE_DB_USER = 'REMOVE_DB_USER';

export const SET_ALL_USERS = 'SET_ALL_USERS';

export const SET_USER = 'SET_USER';

export const SET_APPLICATIONS = 'SET_APPLICATIONS';

export const SET_APPLICATION = 'SET_APPLICATION';

export const SET_DATABASES = 'SET_DATABASES';

export const SET_DATABASE = 'SET_DATABASE';

export const SET_APPLICATION_SCREENS = 'SET_APPLICATION_SCREENS';

export const SET_ALL_APPLICATION_SCREEN_RIGHTS =
  'SET_ALL_APPLICATION_SCREEN_RIGHTS';

export const SET_ALL_APPLICATION_SCREEN_RIGHTS_FOR_SELECTED_USER =
  'SET_ALL_APPLICATION_SCREEN_RIGHTS_FOR_SELECTED_USER';

export const SET_ALL_USER_PERMISSIONS = 'SET_ALL_USER_PERMISSIONS';

export const SET_ALL_USER_PERMISSIONS_FOR_SELECTED_USER =
  'SET_ALL_USER_PERMISSIONS_FOR_SELECTED_USER';
